import { Link } from "wouter";
import { LayoutDashboard, Sparkles, ArrowRight } from "lucide-react";
import { useTenantConfig, resolveIcon } from "@/lib/tenant-config";
import { useGeneratedDashboards } from "@/lib/generated-dashboards";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";

function dashboardRouteFor(sectionId: string, route: string): string {
  if (route === "/" || route === "") {
    return `/dashboards/${sectionId}`;
  }
  return route;
}

export default function Dashboards() {
  const { config, isLoading } = useTenantConfig();
  const { dashboards: generated } = useGeneratedDashboards();

  if (isLoading || !config) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-8 w-48" />
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-40 rounded-xl" />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center gap-3">
        <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
          <LayoutDashboard className="w-5 h-5 text-primary" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-foreground tracking-tight">Dashboards</h1>
          <p className="text-xs text-muted-foreground">
            Pre-built {config.branding?.industry || "domain"} dashboards plus anything you generate with Copilot.
          </p>
        </div>
      </div>

      <section className="space-y-3">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          Built-in dashboards
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {config.sections.map((section) => {
            const Icon = resolveIcon(section.icon);
            const href = dashboardRouteFor(section.id, section.route);
            const subtitle =
              section.kpis?.length
                ? `${section.kpis.length} KPIs · ${section.charts?.length || 0} charts`
                : `${section.charts?.length || 0} charts`;
            return (
              <Link key={section.id} href={href}>
                <Card
                  className="group cursor-pointer hover:border-primary/40 hover:shadow-md transition-all"
                  data-testid={`dashboard-card-${section.id}`}
                >
                  <CardHeader className="pb-2">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
                        <Icon className="w-4.5 h-4.5 text-primary" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <CardTitle className="text-sm font-semibold truncate">{section.label}</CardTitle>
                        <CardDescription className="text-[11px] mt-0.5">{subtitle}</CardDescription>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent className="pt-0 flex items-center justify-between">
                    <Badge variant="secondary" className="text-[10px] uppercase tracking-wider">
                      Built-in
                    </Badge>
                    <ArrowRight className="w-4 h-4 text-muted-foreground group-hover:text-primary transition-colors" />
                  </CardContent>
                </Card>
              </Link>
            );
          })}
        </div>
      </section>

      {generated.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
            Generated by Copilot
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {generated.map((d) => (
              <Link key={d.id} href={d.route}>
                <Card
                  className="group cursor-pointer hover:border-primary/40 hover:shadow-md transition-all"
                  data-testid={`dashboard-card-${d.id}`}
                >
                  <CardHeader className="pb-2">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
                        <Sparkles className="w-4.5 h-4.5 text-primary" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <CardTitle className="text-sm font-semibold truncate">{d.title}</CardTitle>
                        <CardDescription className="text-[11px] mt-0.5">
                          Created {new Date(d.createdAt).toLocaleDateString()}
                        </CardDescription>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent className="pt-0 flex items-center justify-between">
                    <Badge variant="outline" className="text-[10px] uppercase tracking-wider">
                      Custom
                    </Badge>
                    <ArrowRight className="w-4 h-4 text-muted-foreground group-hover:text-primary transition-colors" />
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
