import { useEffect, useRef, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Loader2, Check, Sparkles, CircleDashed, AlertTriangle } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * Drives the auto-mode multiagent pipeline and renders live progress.
 *
 *   POST /api/projects/:id/dashboards/auto-generate  (SSE)
 *   -> data: {"type":"plan","phases":[...],"lenses":[...]}
 *      data: {"type":"phase","name":"profiler","status":"done","detail":"..."}
 *      data: {"type":"finding","lens":"descriptive","summary":"..."}
 *      data: {"type":"phase","name":"visualization","charts":6}
 *      data: {"type":"done","dashboardId":12,"report":"# ...","charts":6}
 */
type Phase = { id: string; label: string };

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  projectId: number;
  onCreated: (dashboardId: number) => void;
}

export function AutoGenerateDialog({ open, onOpenChange, projectId, onCreated }: Props) {
  const [phases, setPhases] = useState<Phase[]>([]);
  const [lenses, setLenses] = useState<string[]>([]);
  const [completed, setCompleted] = useState<Set<string>>(new Set());
  const [findings, setFindings] = useState<Record<string, string>>({});
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [warnings, setWarnings] = useState<string[]>([]);
  const [result, setResult] = useState<{ dashboardId: number; charts: number } | null>(null);
  const startedRef = useRef(false);

  // Kick off the pipeline once when the dialog opens.
  useEffect(() => {
    if (!open || startedRef.current) return;
    startedRef.current = true;
    void run();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // Reset everything when the dialog closes so a re-open starts fresh.
  useEffect(() => {
    if (open) return;
    startedRef.current = false;
    setPhases([]);
    setLenses([]);
    setCompleted(new Set());
    setFindings({});
    setRunning(false);
    setError(null);
    setWarnings([]);
    setResult(null);
  }, [open]);

  const markDone = (id: string) => setCompleted((prev) => new Set(prev).add(id));

  const handleEvent = (evt: any, lensCount: () => number) => {
    switch (evt.type) {
      case "plan":
        setPhases(evt.phases ?? []);
        setLenses(evt.lenses ?? []);
        break;
      case "phase":
        if (["profiler", "cleaning", "merging", "visualization"].includes(evt.name)) markDone(evt.name);
        break;
      case "finding":
        setFindings((prev) => {
          const next = { ...prev, [evt.lens]: evt.summary || "" };
          if (Object.keys(next).length >= lensCount()) markDone("analysis");
          return next;
        });
        break;
      case "warning":
        setWarnings((prev) => [...prev, evt.message]);
        break;
      case "done":
        markDone("analysis");
        markDone("assemble");
        setRunning(false);
        setResult({ dashboardId: evt.dashboardId, charts: evt.charts ?? 0 });
        break;
      case "error":
        setRunning(false);
        setError(evt.message || "Dashboard generation failed.");
        break;
    }
  };

  const run = async () => {
    setRunning(true);
    setError(null);
    const lensesRef = { current: 5 };
    try {
      const res = await fetch(`/api/projects/${projectId}/dashboards/auto-generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({}),
      });
      if (!res.ok || !res.body) {
        throw new Error(`Request failed (${res.status})`);
      }
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";
      // eslint-disable-next-line no-constant-condition
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const chunks = buffer.split("\n\n");
        buffer = chunks.pop() ?? "";
        for (const chunk of chunks) {
          const line = chunk.split("\n").find((l) => l.startsWith("data:"));
          if (!line) continue;
          try {
            const evt = JSON.parse(line.slice(5).trim());
            if (evt.type === "plan" && Array.isArray(evt.lenses)) lensesRef.current = evt.lenses.length || 5;
            handleEvent(evt, () => lensesRef.current);
          } catch {
            /* ignore malformed chunk */
          }
        }
      }
    } catch (err) {
      setRunning(false);
      setError(err instanceof Error ? err.message : "Dashboard generation failed.");
    }
  };

  const activeId = phases.find((p) => !completed.has(p.id))?.id;

  return (
    <Dialog open={open} onOpenChange={(o) => { if (!running) onOpenChange(o); }}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-primary" /> Generating your dashboard
          </DialogTitle>
          <DialogDescription>
            A multi-agent system is profiling, cleaning, merging, analysing and visualising your data.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-2 py-1">
          {phases.length === 0 && running && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="w-4 h-4 animate-spin" /> Starting agents…
            </div>
          )}
          {phases.map((p) => {
            const done = completed.has(p.id);
            const active = p.id === activeId && running;
            return (
              <div key={p.id} className="space-y-1">
                <div className={cn("flex items-center gap-2 text-sm", done ? "text-foreground" : active ? "text-foreground" : "text-muted-foreground")}>
                  {done ? (
                    <Check className="w-4 h-4 text-green-600" />
                  ) : active ? (
                    <Loader2 className="w-4 h-4 animate-spin text-primary" />
                  ) : (
                    <CircleDashed className="w-4 h-4 opacity-50" />
                  )}
                  <span>{p.label}</span>
                </div>
                {p.id === "analysis" && Object.keys(findings).length > 0 && (
                  <ul className="ml-6 space-y-0.5">
                    {lenses.map((l) =>
                      findings[l] ? (
                        <li key={l} className="text-xs text-muted-foreground">
                          <span className="font-medium capitalize">{l}:</span> {findings[l].slice(0, 90)}
                          {findings[l].length > 90 ? "…" : ""}
                        </li>
                      ) : null,
                    )}
                  </ul>
                )}
              </div>
            );
          })}

          {warnings.map((w, i) => (
            <p key={i} className="text-xs text-amber-600 flex items-center gap-1.5">
              <AlertTriangle className="w-3 h-3" /> {w}
            </p>
          ))}
          {error && (
            <p className="text-sm text-red-600 flex items-center gap-1.5">
              <AlertTriangle className="w-4 h-4" /> {error}
            </p>
          )}
          {result && (
            <p className="text-sm text-green-700 flex items-center gap-1.5">
              <Check className="w-4 h-4" /> Dashboard ready with {result.charts} chart{result.charts === 1 ? "" : "s"}.
            </p>
          )}
        </div>

        <DialogFooter>
          {result ? (
            <Button onClick={() => { onCreated(result.dashboardId); onOpenChange(false); }} data-testid="view-dashboard">
              View dashboard
            </Button>
          ) : error ? (
            <>
              <Button variant="ghost" onClick={() => onOpenChange(false)}>Close</Button>
              <Button onClick={() => { startedRef.current = false; void run(); }}>Retry</Button>
            </>
          ) : (
            <Button variant="ghost" disabled={running} onClick={() => onOpenChange(false)}>
              {running ? "Working…" : "Close"}
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
