"""Dashboard generation helpers — port of the chart-normalisation + KPI
synthesis logic from `data-modeler/executor.ts`.
"""
from __future__ import annotations

import re
import time
from typing import Any

from ...db import pool as db
from ...db.introspection import warehouse_columns_grouped
from ...db.repositories import dashboards as repo
from ...db.schemas import quote_ident, warehouse_schema
from ..shared.validation import assert_schema_scope, assert_select_only

NUMERIC_TYPE = re.compile(r"int|float|numeric|double|real|decimal|money|serial", re.IGNORECASE)
BOOL_TYPE = re.compile(r"bool", re.IGNORECASE)
NUM_KEYWORD = re.compile(r"revenue|amount|sales|price|value|total|cost|fee|premium|spend|deal|commission", re.IGNORECASE)
CAT_KEYWORD = re.compile(r"customer|category|region|product|user|type|status|name|brand|city|segment|tier|owner|broker|supplier", re.IGNORECASE)
# Categorical column that buckets entities into performance tiers (built by the guided KPI agent).
PERF_KEYWORD = re.compile(r"performance|perf_cat|tier|grade|rating", re.IGNORECASE)


def _col_to_label(raw: str) -> str:
    return re.sub(r"[_\s]+", " ", raw).strip().title()


def _value_is_numeric(v: Any) -> bool:
    if v is None or v == "":
        return False
    try:
        float(v)
        return True
    except (TypeError, ValueError):
        return False


def _column_is_numeric(rows: list[dict[str, Any]], key: str) -> bool:
    if not rows:
        return False
    n = sum(1 for r in rows if _value_is_numeric(r.get(key)))
    return n / len(rows) >= 0.7


def _base36(n: int) -> str:
    if n == 0:
        return "0"
    digits = "0123456789abcdefghijklmnopqrstuvwxyz"
    out = ""
    while n:
        n, rem = divmod(n, 36)
        out = digits[rem] + out
    return out


def normalize_agent_charts(charts: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Validate + repair visualization charts so none render as bare numbers.

    Drops KPI charts (regenerated by ensure_project_kpis), drops charts with no
    usable data, infers missing xKey/yKey, downgrades bad scatters to bar.
    """
    out: list[dict[str, Any]] = []
    for chart in charts:
        if chart.get("chartType") == "kpi":
            continue
        cfg = dict(chart.get("config") or {})
        data = cfg.get("data") if isinstance(cfg.get("data"), list) else []
        if not data:
            continue
        keys = list(data[0].keys()) if isinstance(data[0], dict) else []
        if not keys:
            continue

        numeric_keys = [k for k in keys if _column_is_numeric(data, k)]
        categorical_keys = [k for k in keys if k not in numeric_keys]

        x_key = cfg.get("xKey") if isinstance(cfg.get("xKey"), str) and cfg.get("xKey") in keys else None
        y_key: Any = cfg.get("yKey")

        ctype = chart.get("chartType")
        if ctype in ("scatter", "bubble"):
            if len(numeric_keys) < 2:
                if not categorical_keys or not numeric_keys:
                    continue
                chart["chartType"] = "bar"
                x_key = categorical_keys[0]
                y_key = numeric_keys[0]
            else:
                if not x_key or x_key not in numeric_keys:
                    x_key = numeric_keys[0]
                y_str = y_key[0] if isinstance(y_key, list) and y_key else y_key
                if isinstance(y_str, str) and y_str in numeric_keys and y_str != x_key:
                    y_key = y_str
                else:
                    y_key = next((k for k in numeric_keys if k != x_key), numeric_keys[1] if len(numeric_keys) > 1 else numeric_keys[0])
        else:
            if not categorical_keys or not numeric_keys:
                continue
            if not x_key or x_key not in categorical_keys:
                x_key = categorical_keys[0]
            keep_array = isinstance(y_key, list) and all(isinstance(k, str) and k in numeric_keys for k in y_key)
            if not keep_array:
                y_str = y_key[0] if isinstance(y_key, list) and y_key else y_key
                y_key = y_str if isinstance(y_str, str) and y_str in numeric_keys else numeric_keys[0]

        cfg.update({"xKey": x_key, "yKey": y_key})
        chart["config"] = cfg
        out.append(chart)
    return out


async def ensure_project_kpis(project_id: int, dash_id: int, preferred_table: str | None = None) -> None:
    """Guarantee up to 4 KPI stat cards by querying the warehouse directly.
    Skips silently on any failure so a missing KPI never blocks creation.

    When `preferred_table` is given (the guided KPI table), its columns drive the
    cards — including a performance-tier count (e.g. underperforming entities) so
    the cards reflect what the user asked about rather than a generic total."""
    existing = await repo.charts_for_dashboard(dash_id)
    existing_kpis = [c for c in existing if c["chart_type"] == "kpi"]
    if len(existing_kpis) >= 4:
        return

    existing_titles = {c["title"].lower() for c in existing}
    max_position = max((c["position"] or 0 for c in existing), default=-1)

    try:
        tables = await warehouse_columns_grouped(project_id)
    except Exception:  # noqa: BLE001
        return
    if not tables:
        return

    chosen = next((t for t in tables if t["tableName"] == preferred_table), None) if preferred_table else None
    if not chosen:
        chosen = next((t for t in tables if any(NUMERIC_TYPE.search(c["type"]) and NUM_KEYWORD.search(c["name"]) for c in t["columns"])), None)
    if not chosen:
        chosen = next((t for t in tables if any(NUMERIC_TYPE.search(c["type"]) for c in t["columns"])), None)
    if not chosen:
        chosen = tables[0]

    numeric_cols = [c["name"] for c in chosen["columns"] if NUMERIC_TYPE.search(c["type"])]
    categorical_cols = [c["name"] for c in chosen["columns"] if not NUMERIC_TYPE.search(c["type"]) and not BOOL_TYPE.search(c["type"])]
    best_numeric = next((c for c in numeric_cols if NUM_KEYWORD.search(c)), numeric_cols[0] if numeric_cols else None)
    best_categorical = next((c for c in categorical_cols if CAT_KEYWORD.search(c)), categorical_cols[0] if categorical_cols else None)
    perf_col = next((c for c in categorical_cols if PERF_KEYWORD.search(c)), None)

    schema = warehouse_schema(project_id)
    qualified = f"{quote_ident(schema)}.{quote_ident(chosen['tableName'])}"

    candidates: list[dict[str, str]] = [{"title": "Total Records", "expr": "COUNT(*)"}]
    # Lead with the performance-tier count so the user's question is answered up front.
    if perf_col:
        candidates.insert(0, {
            "title": "Underperforming",
            "expr": f"COUNT(*) FILTER (WHERE {quote_ident(perf_col)} ILIKE '%underperf%')",
        })
    if best_numeric:
        candidates.append({"title": f"Avg {_col_to_label(best_numeric)}", "expr": f"ROUND(AVG({quote_ident(best_numeric)})::numeric, 2)"})
        candidates.append({"title": f"Total {_col_to_label(best_numeric)}", "expr": f"SUM({quote_ident(best_numeric)})"})
    if best_categorical:
        candidates.append({"title": f"Distinct {_col_to_label(best_categorical)}", "expr": f"COUNT(DISTINCT {quote_ident(best_categorical)})"})

    needed = 4 - len(existing_kpis)
    to_create = [c for c in candidates if c["title"].lower() not in existing_titles][:needed]
    if not to_create:
        return

    values: list[dict[str, Any]] = []
    pos = max_position + 1
    async with db.get_pool().connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute("SET statement_timeout = 5000")
            for cand in to_create:
                kpi_sql = f"SELECT {cand['expr']} AS kpi_value FROM {qualified}"
                try:
                    assert_select_only(kpi_sql)
                    assert_schema_scope(kpi_sql, [schema])
                    await cur.execute(kpi_sql)
                    rows = await cur.fetchall()
                    data = rows[:1]
                    if not data:
                        continue
                    values.append({
                        "dashboard_id": dash_id,
                        "title": cand["title"],
                        "chart_type": "kpi",
                        "config": {"xKey": "kpi_value", "yKey": "kpi_value", "data": data, "sql": kpi_sql},
                        "position": pos,
                        "col_span": 1,
                    })
                    pos += 1
                except Exception:  # noqa: BLE001
                    continue

    if values:
        await repo.insert_charts(values)


async def create_project_dashboard(
    project_id: int, title: str, charts: list[dict[str, Any]], report_md: str | None = None,
    kpi_table: str | None = None,
) -> dict[str, Any]:
    if not title or not isinstance(charts, list) or not charts:
        return {"error": "title and at least one chart are required"}

    safe_title = title.strip()[:255]
    flat_table_name = f"proj_{project_id}_dash_{_base36(int(time.time() * 1000))}"

    # The narrative report (auto mode) rides in agent_log; otherwise keep the
    # original provenance string the manual data-modeler used.
    agent_log = report_md if report_md else f"Generated by DataModelerAgent for project {project_id}"

    dashboard = await repo.insert_dashboard(
        name=safe_title,
        flat_table_name=flat_table_name,
        agent_log=agent_log,
    )

    normalized = normalize_agent_charts(charts)
    if normalized:
        await repo.insert_charts(
            [
                {
                    "dashboard_id": dashboard["id"],
                    "title": c["title"],
                    "chart_type": c["chartType"],
                    "config": c["config"],
                    "position": i,
                    "col_span": 1,
                }
                for i, c in enumerate(normalized)
            ]
        )

    await ensure_project_kpis(project_id, dashboard["id"], preferred_table=kpi_table)
    return {"dashboardId": dashboard["id"], "name": safe_title, "chartCount": len(normalized)}
